name: Actualizar Lista Scraper Acestream API

on:
  schedule:
    - cron: '19 * * * *'  # Ejecutar cada 1 hora (minuto 19)
  workflow_dispatch:  # Permitir ejecución manual

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: repo-main-writes
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v7

    - name: Configurar Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install requests
        pip install fuzzywuzzy
        pip install python-Levenshtein

    - name: Ejecutar script de scraping
      run: python script_scraper_acestream_api.py

    - name: Subir archivo M3U
      uses: ./.github/actions/commit-and-push
      with:
        files: lista_scraper_acestream_api.m3u
        commit_message: Actualizar lista M3U scraper Acestream API
